// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Apple.AppleWatchReprationPreis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batteri_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AppleWatchReprationPreis");
                });

            modelBuilder.Entity("Core.Entities.Apple.ImacReparation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bakkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bakkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_front_Kamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_ØreHøjtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("front_Kamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ØreHøjtale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ImacReparation");
                });

            modelBuilder.Entity("Core.Entities.Apple.IpadReprationPreis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Antenne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagcover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Home_Knap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kamera_Glas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Antenne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagcover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Home_Knap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Kamera_Glas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Panserglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_SIM_KORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_SkærmLcd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_WIFI_Antenne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Panserglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIM_KORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkærmLcd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WIFI_Antenne")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IpadReprationPreis");
                });

            modelBuilder.Entity("Core.Entities.Apple.IphoneReprationPreis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BagglasOgRamme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKameraNærhedsensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_BagglasOgRamme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKameraNærhedsensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_SkærmOEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_SkærmOrgnal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_TændSluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_VolumeLydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkærmOEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkærmOrgnal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TændSluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeLydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IphoneReprationPreis");
                });

            modelBuilder.Entity("Core.Entities.Apple.MacbookReparation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blæser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bundplade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Blæser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bundplade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Styresystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tastetur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_TrackPad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Styresystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tastetur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackPad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MacbookReparation");
                });

            modelBuilder.Entity("Core.Entities.Computer.CpmputerReparationPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_F")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_G")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_H")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_I")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_K")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pris_M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_F")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_G")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_H")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_I")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_K")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ydelse_M")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CpmputerReparationPrice");
                });

            modelBuilder.Entity("Core.Entities.Huawei.Huawei_Mate_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Huawei_Mate_Serien");
                });

            modelBuilder.Entity("Core.Entities.Huawei.Huawei_P_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Huawei_P_Serien");
                });

            modelBuilder.Entity("Core.Entities.Images_Tabel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageName = "hero-b.jpg"
                        },
                        new
                        {
                            ID = 2,
                            ImageName = "Smadret-skaerm.webp"
                        },
                        new
                        {
                            ID = 3,
                            ImageName = "Smartphone-rep.webp"
                        },
                        new
                        {
                            ID = 4,
                            ImageName = "ikon1-04.svg"
                        },
                        new
                        {
                            ID = 5,
                            ImageName = "mobile-app-2-03.svg"
                        },
                        new
                        {
                            ID = 6,
                            ImageName = "mobile-app-6-06.svg"
                        },
                        new
                        {
                            ID = 7,
                            ImageName = "iphone.webp"
                        },
                        new
                        {
                            ID = 8,
                            ImageName = "AppleWatch.webp"
                        },
                        new
                        {
                            ID = 9,
                            ImageName = "iPad.webp"
                        },
                        new
                        {
                            ID = 10,
                            ImageName = "macbook.webp"
                        },
                        new
                        {
                            ID = 11,
                            ImageName = "IMac.webp"
                        },
                        new
                        {
                            ID = 12,
                            ImageName = "GalaxyNote.webp"
                        },
                        new
                        {
                            ID = 13,
                            ImageName = "GalaxyA.webp"
                        },
                        new
                        {
                            ID = 14,
                            ImageName = "GalaxyJ.webp"
                        },
                        new
                        {
                            ID = 15,
                            ImageName = "xcover.webp"
                        },
                        new
                        {
                            ID = 16,
                            ImageName = "GalaxyNote.webp"
                        },
                        new
                        {
                            ID = 17,
                            ImageName = "P-Serien.webp"
                        },
                        new
                        {
                            ID = 18,
                            ImageName = "Mate-Serien.webp"
                        },
                        new
                        {
                            ID = 19,
                            ImageName = "Mate-Serien.webp"
                        },
                        new
                        {
                            ID = 20,
                            ImageName = "Xperia-Z.webp"
                        },
                        new
                        {
                            ID = 21,
                            ImageName = "Xperia-X.webp"
                        },
                        new
                        {
                            ID = 22,
                            ImageName = "Xperia-Top.webp"
                        },
                        new
                        {
                            ID = 23,
                            ImageName = "Motorola-G.webp"
                        },
                        new
                        {
                            ID = 24,
                            ImageName = "Motorola-E.webp"
                        },
                        new
                        {
                            ID = 25,
                            ImageName = "Motorola-One.webp"
                        },
                        new
                        {
                            ID = 26,
                            ImageName = "Motorola-Edge.webp"
                        });
                });

            modelBuilder.Entity("Core.Entities.Motorola.MotorolaEdge_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MotorolaEdge_Serien");
                });

            modelBuilder.Entity("Core.Entities.Motorola.MotorolaOne_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MotorolaOne_Serien");
                });

            modelBuilder.Entity("Core.Entities.Motorola.Motorola_E_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Motorola_E_Serien");
                });

            modelBuilder.Entity("Core.Entities.Motorola.Motorola_G_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Motorola_G_Serien");
                });

            modelBuilder.Entity("Core.Entities.Nokia.NokiaRepartionPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NokiaRepartionPrice");
                });

            modelBuilder.Entity("Core.Entities.Oneplus.OneplusReparation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_rensning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rensning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OneplusReparation");
                });

            modelBuilder.Entity("Core.Entities.Samsung.GalaxyNoteSerien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("GalaxyNoteSerien");
                });

            modelBuilder.Entity("Core.Entities.Samsung.Galaxy_A_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Galaxy_A_Serien");
                });

            modelBuilder.Entity("Core.Entities.Samsung.Galaxy_J_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Galaxy_J_Serien");
                });

            modelBuilder.Entity("Core.Entities.Samsung.Galaxy_S_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Galaxy_S_Serien");
                });

            modelBuilder.Entity("Core.Entities.Samsung.Galaxy_Xcover_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Galaxy_Xcover_Serien");
                });

            modelBuilder.Entity("Core.Entities.Sony.XperiaTopModeller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("XperiaTopModeller");
                });

            modelBuilder.Entity("Core.Entities.Sony.Xperia_X_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Xperia_X_Serien");
                });

            modelBuilder.Entity("Core.Entities.Sony.Xperia_Z_Serien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagglas_Ramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Bagkamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Batteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Fejlfinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_FrontKamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Højtale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ladestik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skærm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tænd_Sluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vibrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_Lydløs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ørehøjtaler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Xperia_Z_Serien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
